CREATE DATABASE AulaPWIII; 
GO 

CREATE TABLE USUARIO (
  IDUSUARIO INTEGER IDENTITY(1,1) NOT NULL ,
  USERUSUARIO VARCHAR(20) NOT NULL,
  PASSUSUARIO VARCHAR(40) NOT NULL,
  TIPOUSUARIO INTEGER NOT NULL,
  STATUSUSUARIO INTEGER NOT NULL,
  PRIMARY KEY(IDUSUARIO)
);


CREATE TABLE PESSOA (
  IDPESSOA INTEGER IDENTITY(1,1) NOT NULL ,
  IDUSUARIO INTEGER  NOT NULL,
  CPFPESSOA VARCHAR(14) NOT NULL,
  TELPESSOA VARCHAR(11) NOT NULL,
  EMAILPESSOA VARCHAR(100) NOT NULL,
  ENDPESSOA VARCHAR(150) NOT NULL,
  NOMEPESSOA VARCHAR(20),
  SOBRENOMEPESSOA VARCHAR(20),
  PRIMARY KEY(IDPESSOA)
);
















--DELETE
--Usuário 
/*EXCLUINDO UMA INFORMAÇÃO DO INSERT  USUARIO*/
DELETE FROM USUARIO WHERE IDUSUARIO = 2;

/* EXCLUINDO INFORMAÇÃO */ 
DECLARE @NOME VARCHAR(10) 
DECLARE @INTNOME INT 

SELECT @NOME = 'SILVIA'
SELECT @NOME

DELETE  PESSOA 
WHERE NOMEPESSOA = @NOME 


--UPDATE
